---

- name: Airflow | Install
  import_tasks: install.yml
  tags:
    - install

- name: Airflow | Config
  import_tasks: config.yml
  tags:
    - config

- name: Airflow | Service
  import_tasks: service.yml
  tags:
    - service
